//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalInfo
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int adView = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int androidVersion = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int buildHost = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int carrierName = 2131099653;
			
			// aapt resource value: 0x7f06000a
			public const int cdmaECIO_4 = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int cdmaSignal_3 = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int evdoECIO_6 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int evdoSNR_7 = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int evdoSignal_5 = 2131099657;
			
			// aapt resource value: 0x7f060014
			public const int gsmBitError_2 = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int gsmSigStrength_1 = 2131099667;
			
			// aapt resource value: 0x7f060011
			public const int lteCQI_12 = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int lteRSRQ_10 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int lteSNR_11 = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int lteSigStrength_8 = 2131099666;
			
			// aapt resource value: 0x7f060000
			public const int main = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int networkType_13 = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int phoneModel = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int phoneName = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int rsrpSignal_9 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int rssiSignal_14 = 2131099662;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000b
			public const int androidVersion = 2130968587;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040019
			public const int buildHost = 2130968601;
			
			// aapt resource value: 0x7f04000c
			public const int carrierName = 2130968588;
			
			// aapt resource value: 0x7f040003
			public const int cdmaECIO = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int cdmaSignal = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int cdmaTitle = 2130968577;
			
			// aapt resource value: 0x7f04001a
			public const int contentDescTag = 2130968602;
			
			// aapt resource value: 0x7f040018
			public const int copyright = 2130968600;
			
			// aapt resource value: 0x7f040005
			public const int evdoECIO = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int evdoSNR = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int evdoSignal = 2130968580;
			
			// aapt resource value: 0x7f040015
			public const int gsmBitError = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int gsmSigStrength = 2130968596;
			
			// aapt resource value: 0x7f040012
			public const int lteCQI = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int lteRSRQ = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int lteSNR = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int lteSigStrength = 2130968595;
			
			// aapt resource value: 0x7f040007
			public const int lteTitle = 2130968583;
			
			// aapt resource value: 0x7f040016
			public const int na = 2130968598;
			
			// aapt resource value: 0x7f04000d
			public const int networkType = 2130968589;
			
			// aapt resource value: 0x7f040009
			public const int phoneInfo = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int phoneModel = 2130968586;
			
			// aapt resource value: 0x7f040017
			public const int phoneName = 2130968599;
			
			// aapt resource value: 0x7f04000e
			public const int rsrpSignal = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int rssiSignal = 2130968591;
			
			// aapt resource value: 0x7f040008
			public const int saveScreenShot = 2130968584;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int MainTheme = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
